version: "3.7"

networks:
  default:
    driver: bridge

services:
  app:
    build: .
    container_name: app
    restart: always
    env_file:
      - .env
    command:
      "./start.sh"
    volumes:
      - 'app_log:/app/logs'

  nginx:
    image: nginx:1.18
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  app_log:
    driver: local
